spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/databse-browser
    username: sa
    password:

#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: update